### ISSUE TITLE
Unable to compile a Reaction snippet from the NDK3.2 

### ISSUE THREAD

**Issue by rosneru** [bebbo/amiga-gcc#384]
The attached file `Layout1.c` is one of the examples from the NDK3.2 and like most of these examples it shows how to create programs with Reaction.

It makes heavy use of the macros defined in `reaction_macros.h` which I also attached here. But  `Layout1.c` fails to compile stating:
```
$ m68k-amigaos-gcc Layout1.c

    Layout1.c: In function 'main':
    Layout1.c:307:0: error: unterminated argument list invoking macro "NewObject"
     }
    
    Layout1.c:66:10: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
      gParent = VGroupObject,
              ^
    Layout1.c:66:2: error: expected ';' at end of input
      gParent = VGroupObject,
      ^~~~~~~
    Layout1.c:66:2: error: expected declaration or statement at end of input

$
```

With SAS-C it works with this commandline:

```
sc LINK Layout1.c LIB lib:reaction.lib NOSTACKCHECK 
```

What do I have to do to make it work with gcc 6.5?

[Layout1.c.md](https://github.com/bebbo/amiga-gcc/files/14431549/Layout1.c.md)
[reaction_macros.h.md](https://github.com/bebbo/amiga-gcc/files/14431550/reaction_macros.h.md)

**Comment by bebbo** [comment]
1. Update your amiga-gcc, and at least rebuild libnix:
```
make update
make clean-libnix
make libnix
```

2. You have to define `NO_INLINE_STDARG`. 
```
m68k-amigaos-gcc Layout1.c -o Layout1 -noixemul -Os  -DNO_INLINE_STDARG
```
![grafik](https://github.com/bebbo/amiga-gcc/assets/16560863/51a6647e-bf9e-4c79-8db5-4cefff9c5027)

**Comment by rosneru** [comment]
Thank you, this works!

I have one last question regarding Reaction:
When compiling another example from the 3.2 NDK, `Cooser1.c` (attached) it still fails. Because there is a function call of `FreeChooserLabels()` which is declared in `clib/reaction_lib_protos.h` and uses code from linker library `reaction.lib`.

The thing is
- reaction.lib seems not to be part of the NDK (I don't find it there).
- But in `opt/amiga/m68k-amigaos/vbcc/lib` it exists
- In my SAS-C installation at home it also seems to exist because I remember compiling `chooser1.c` successfully with the command given in the file

    sc LINK Chooser1.c LIB lib:reaction.lib NOSTACKCHECK

Is there a way to use this lib from gcc?

[Chooser1.c.md](https://github.com/bebbo/amiga-gcc/files/14434463/Chooser1.c.md)

**Comment by bebbo** [comment]
try copying that lib into `opt/amiga/lib` and add `-lreaction` ...

**Comment by rosneru** [comment]
Unfortunately it didn't work:

    m68k-amigaos/bin/ld: cannot find -lreaction: No such file or directory

I copied it to `/opt/amiga` and also to `/opt/amiga/m68k-amigaos/lib`. I also noticed that apart from the copied `reaction.lib` all other files in those directories have a `.a` extension.

**Comment by bebbo** [comment]
rename it to `libreaction.a`

**Comment by rosneru** [comment]
This works:-)
Thank you!
