### ISSUE TITLE
Cannot build on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by hitman-codehq** [bebbo/amiga-gcc#342]
When trying to perform a build on Ubuntu 22.04, I get the following compiler error:

/home/colin/Source/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c:55:23: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   if (!entry || !(str=FindToolType(tt,entry))

This looks like it is a problem with the Amiga OS NDK, rather than the version of GCC or Ubuntu that I am using.  This is with the latest version of the code from this repo and I have done a "git clean -dfx" to make sure all old sub projects and archives have been deleted.

If there is anything I can do to assist in fixing this, please don't hesitate to ask.

Many thanks!

**Comment by hitman-codehq** [comment]
Sorry, false alarm.  I forgot to remote the projects directory before doing a rebuild.  It's compiling again now!
