### ISSUE TITLE
Build on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by alpyre** [bebbo/amiga-gcc#221]
**OS:** Ubuntu 20.04.2 LTS
**gcc version :** 9.3.0

**Steps taken:**
```
sudo apt install make wget git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex bison gettext texinfo ncurses-dev autoconf rsync
mkdir /opt/temp
cd /opt/temp
git clone https://github.com/bebbo/amiga-gcc
cd amiga-gcc
make update
make all PREFIX=/opt/amiga/compilers/m68k-amigaos/gcc_6.5.0b
```
**Returned messages:**
```
configure binutils...
configure binutils...done
make binutils bfd...
make binutils bfd...done
make binutils gas...
make binutils gas...done
make binutils binutils...
make binutils binutils...done
make binutils ld...
make binutils ld...done
install binutils...
install binutils...done
configure gcc...
configure gcc...done
make gcc...
make gcc...done
install gcc...
install gcc...done
make binutils configure gdb...
make binutils configure gdb...done
make binutils gdb libs...
make binutils gdb libs...done
make binutils gdb...
make binutils gdb...failed
make[3]: Leaving directory '/opt/temp/amiga-gcc/build-Linux/binutils/gdb'
  CXXLD  gdb
/usr/bin/ld: init.o: in function `initialize_all_files()':
init.c:(.text+0xb): undefined reference to `_initialize_ser_hardw()'
/usr/bin/ld: init.c:(.text+0x10): undefined reference to `_initialize_ser_p()'
/usr/bin/ld: init.c:(.text+0x1f): undefined reference to `_initialize_m()'
/usr/bin/ld: init.c:(.text+0x24): undefined reference to `_initialize_m()'
/usr/bin/ld: init.c:(.text+0x29): undefined reference to `_initialize_m()'
/usr/bin/ld: init.c:(.text+0x2e): undefined reference to `_initialize_m()'
/usr/bin/ld: init.c:(.text+0x33): undefined reference to `_initialize_tu()'
/usr/bin/ld: init.c:(.text+0x38): undefined reference to `_initialize_tu()'
/usr/bin/ld: init.c:(.text+0x3d): undefined reference to `_initialize_tu()'
/usr/bin/ld: init.c:(.text+0x42): undefined reference to `_initialize_tu()'
/usr/bin/ld: init.c:(.text+0x47): undefined reference to `_initialize_tu()'
/usr/bin/ld: init.o:init.c:(.text+0x4c): more undefined references to `_initialize_tu()' follow
/usr/bin/ld: init.o: in function `initialize_all_files()':
init.c:(.text+0x5b): undefined reference to `_initialize_gu()'
/usr/bin/ld: init.c:(.text+0x60): undefined reference to `_initialize_d()'
/usr/bin/ld: init.c:(.text+0x6a): undefined reference to `_initialize_array_v()'
/usr/bin/ld: init.c:(.text+0x6f): undefined reference to `_initialize_ch()'
/usr/bin/ld: init.c:(.text+0x74): undefined reference to `_initialize_cl()'
/usr/bin/ld: init.c:(.text+0x7e): undefined reference to `_initialize_common_ut()'
/usr/bin/ld: init.c:(.text+0x83): undefined reference to `_initialize_copy_b()'
/usr/bin/ld: init.c:(.text+0x88): undefined reference to `_initialize_env()'
/usr/bin/ld: init.c:(.text+0x8d): undefined reference to `_initialize_f()'
/usr/bin/ld: init.c:(.text+0x92): undefined reference to `_initialize_format_p()'
/usr/bin/ld: init.c:(.text+0x97): undefined reference to `_initialize_funct()'
/usr/bin/ld: init.c:(.text+0x9c): undefined reference to `_initialize_lookup_name_()'
/usr/bin/ld: init.c:(.text+0xb5): undefined reference to `_initialize_opt()'
/usr/bin/ld: init.c:(.text+0xba): undefined reference to `_initialize_parse_connect()'
/usr/bin/ld: init.c:(.text+0xbf): undefined reference to `_initialize_ma()'
/usr/bin/ld: init.c:(.text+0xc4): undefined reference to `_initialize_mkd()'
/usr/bin/ld: init.c:(.text+0xdd): undefined reference to `_initialize_str()'
/usr/bin/ld: init.c:(.text+0xe7): undefined reference to `_initialize_tracepo()'
/usr/bin/ld: init.c:(.text+0xec): undefined reference to `_initialize_tu()'
/usr/bin/ld: init.c:(.text+0xf6): undefined reference to `_initialize_ut()'
/usr/bin/ld: init.c:(.text+0xfb): undefined reference to `_initialize_vec_ut()'
/usr/bin/ld: init.c:(.text+0x100): undefined reference to `_initialize_xml_ut()'
/usr/bin/ld: init.c:(.text+0x123): undefined reference to `_initialize_am()'
/usr/bin/ld: init.c:(.text+0x128): undefined reference to `_initialize_am()'
/usr/bin/ld: init.c:(.text+0x12d): undefined reference to `_initialize_gdbarch_ut()'
/usr/bin/ld: init.c:(.text+0x141): undefined reference to `_initialize_break_catch_s()'
/usr/bin/ld: init.c:(.text+0x150): undefined reference to `_initialize_breakpo()'
/usr/bin/ld: init.c:(.text+0x169): undefined reference to `_initialize_compla()'
/usr/bin/ld: init.c:(.text+0x173): undefined reference to `_initialize_copy()'
/usr/bin/ld: init.c:(.text+0x182): undefined reference to `_initialize_cp_ab()'
/usr/bin/ld: init.c:(.text+0x191): undefined reference to `_initialize_cp_valpr()'
/usr/bin/ld: init.c:(.text+0x1a5): undefined reference to `_initialize_d()'
/usr/bin/ld: init.c:(.text+0x1b4): undefined reference to `_initialize_ta()'
/usr/bin/ld: init.c:(.text+0x1be): undefined reference to `_initialize_()'
/usr/bin/ld: init.c:(.text+0x1c3): undefined reference to `_initialize_dwarf_()'
/usr/bin/ld: init.c:(.text+0x1d7): undefined reference to `_initialize_extens()'
/usr/bin/ld: init.c:(.text+0x1e1): undefined reference to `_initialize_f_valpr()'
/usr/bin/ld: init.c:(.text+0x1e6): undefined reference to `_initialize_f()'
/usr/bin/ld: init.c:(.text+0x1f0): undefined reference to `_initialize_f()'
/usr/bin/ld: init.c:(.text+0x1ff): undefined reference to `_initialize_frame_unw()'
/usr/bin/ld: init.c:(.text+0x21d): undefined reference to `_initialize_gnu_v2_ab()'
/usr/bin/ld: init.c:(.text+0x222): undefined reference to `_initialize_gnu_v3_ab()'
/usr/bin/ld: init.c:(.text+0x22c): undefined reference to `_initialize_()'
/usr/bin/ld: init.c:(.text+0x231): undefined reference to `_initialize_()'
/usr/bin/ld: init.c:(.text+0x236): undefined reference to `_initialize_()'
/usr/bin/ld: init.c:(.text+0x23b): undefined reference to `_initialize_()'
/usr/bin/ld: init.c:(.text+0x240): undefined reference to `_initialize_()'
/usr/bin/ld: init.c:(.text+0x245): undefined reference to `_initialize_j()'
/usr/bin/ld: init.c:(.text+0x25e): undefined reference to `_initialize_ma()'
/usr/bin/ld: init.c:(.text+0x263): undefined reference to `_initialize_ma()'
/usr/bin/ld: init.c:(.text+0x268): undefined reference to `_initialize_ma()'
/usr/bin/ld: init.c:(.text+0x277): undefined reference to `_initialize_m()'
/usr/bin/ld: init.c:(.text+0x28b): undefined reference to `_initialize_gdb_osab()'
/usr/bin/ld: init.c:(.text+0x295): undefined reference to `_initialize_pascal_valpr()'
/usr/bin/ld: init.c:(.text+0x29f): undefined reference to `_initialize_pr()'
/usr/bin/ld: init.c:(.text+0x2d6): undefined reference to `_initialize_not()'
/usr/bin/ld: init.c:(.text+0x2e0): undefined reference to `_initialize_run_on_ma()'
/usr/bin/ld: init.c:(.text+0x2e5): undefined reference to `_initialize_ser()'
/usr/bin/ld: init.c:(.text+0x2ea): undefined reference to `_initialize_step_sk()'
/usr/bin/ld: init.c:(.text+0x2ef): undefined reference to `_initialize_sol()'
/usr/bin/ld: init.c:(.text+0x2f4): undefined reference to `_initialize_sol()'
/usr/bin/ld: init.c:(.text+0x312): undefined reference to `_initialize_symf()'
/usr/bin/ld: init.c:(.text+0x317): undefined reference to `_initialize_symf()'
/usr/bin/ld: init.c:(.text+0x31c): undefined reference to `_initialize_symm()'
/usr/bin/ld: init.c:(.text+0x32b): undefined reference to `_initialize_target_connect()'
/usr/bin/ld: init.c:(.text+0x335): undefined reference to `_initialize_target_descr()'
/usr/bin/ld: init.c:(.text+0x344): undefined reference to `_initialize_tracef()'
/usr/bin/ld: init.c:(.text+0x349): undefined reference to `_initialize_tracef()'
/usr/bin/ld: init.c:(.text+0x34e): undefined reference to `_initialize_tracepo()'
/usr/bin/ld: init.c:(.text+0x353): undefined reference to `_initialize_typepr()'
/usr/bin/ld: init.c:(.text+0x358): undefined reference to `_initialize_u()'
/usr/bin/ld: init.c:(.text+0x362): undefined reference to `_initialize_ut()'
/usr/bin/ld: init.c:(.text+0x36c): undefined reference to `_initialize_valpr()'
/usr/bin/ld: init.c:(.text+0x380): undefined reference to `_initialize_cl()'
/usr/bin/ld: init.c:(.text+0x385): undefined reference to `_initialize_cl()'
/usr/bin/ld: init.c:(.text+0x38a): undefined reference to `_initialize_cl()'
/usr/bin/ld: init.c:(.text+0x38f): undefined reference to `_initialize_cl()'
/usr/bin/ld: init.c:(.text+0x394): undefined reference to `_initialize_cl()'
/usr/bin/ld: init.o:init.c:(.text+0x399): more undefined references to `_initialize_cl()' follow
/usr/bin/ld: init.o: in function `initialize_all_files()':
init.c:(.text+0x39e): undefined reference to `_initialize_comp()'
/usr/bin/ld: init.c:(.text+0x3a4): undefined reference to `_initialize_comp()'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1859: gdb] Error 1
make binutils gdb...failed
use less "log/make binutils gdb.log" to view the full log and search for ***
make: *** [Makefile:378: build-Linux/binutils/_gdb] Error 2
```

**Comment by bebbo** [comment]
have a look here: https://stackoverflow.com/questions/63094586/cannot-build-gdb-master-jul-9-2020-on-ubuntu-20-04

**Comment by bebbo** [comment]
best guess: it's a locale issue, try
```
export LC_COLLATE=C
```

**Comment by alpyre** [comment]
Yes changing the locale to EN-UTF8 solved the problem. Thanks.
